[build]
command = "npm run build"
publish = ".next"

[functions]
  directory = "netlify/functions"

[[redirects]]
from = "/api/*"
to = "/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/"
status = 200
