[build]
  command = "npm install && npm run build"
  publish = ".next"

# Catch-all for API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Fixed plugins section (must use double brackets)
[[plugins]]
  package = "@netlify/plugin-nextjs"
