[build]
command = "npm run build"
publish = ".next"

[context.production.environment]
  NODE_VERSION = "18"
  API_URL = "https://api.omnichain.devnet2/"
  CHAIN_ID = "omnichain-devnet-2"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
