[build]
  command = "npm run build"
  publish = ".next"

# Add this EXACT redirect (matches your folder structure)
[[redirects]]
  from = "/api/ce2/*"
  to = "/.netlify/functions/ce2/:splat"
  status = 200
  force = true
