[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src  'self' 'unsafe-eval' 'unsafe-inline';
      style-src   'self' 'unsafe-inline';
      img-src     'self' data:;
      connect-src 'self';
    """

[build]
  command = "npm run build"
  publish = ".next"

[build]
  functions = "api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

  [[plugins]]
  package = "@netlify/plugin-nextjs"
